In [3]:
import numpy as np
                

In [3]:
    print("M");

M


In [8]:
myarr=np.array([6,3,2,4,11],np.int64)

In [9]:
myarr

array([ 6,  3,  2,  4, 11], dtype=int64)

In [10]:
myarr.shape

(5,)

In [14]:
myarr.dtype

dtype('int64')

In [8]:
marray=np.array([[3,2,1],[6,7,8],[6,6,7]])

In [10]:
marray

array([[3, 2, 1],
       [6, 7, 8],
       [6, 6, 7]])

In [11]:
marray.shape

(3, 3)

In [14]:
marray.dtype

dtype('int32')

In [16]:
i=np.arange(15)#print the from 0 to 14

In [17]:
i

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
marray.reshape(9,1)

array([[3],
       [2],
       [1],
       [6],
       [7],
       [8],
       [6],
       [6],
       [7]])

In [26]:
marray.reshape(1,9)

array([[3, 2, 1, 6, 7, 8, 6, 6, 7]])

In [24]:
marray.reshape(9,1)

array([[3],
       [2],
       [1],
       [6],
       [7],
       [8],
       [6],
       [6],
       [7]])

In [21]:
marray.size

9

In [27]:
marray.shape

(3, 3)

In [29]:
e=[[3,2,1],[6,5,4],[6,3,6]]

In [30]:
narray=np.array(e)

In [31]:
e

[[3, 2, 1], [6, 5, 4], [6, 3, 6]]

In [35]:
marray.sum(axis=0)#give in the verti

array([15, 15, 16])

In [36]:
marray.sum(axis=1)#give in the horizon

array([ 6, 21, 19])

In [37]:
marray.T


array([[3, 6, 6],
       [2, 7, 6],
       [1, 8, 7]])

In [39]:
marray.argmin()

2

In [40]:
marray.argmax()

5

In [41]:
marray

array([[3, 2, 1],
       [6, 7, 8],
       [6, 6, 7]])

In [42]:
marray.argmax()#it the index gave of the large number 

5

In [43]:
marray.min()

1